### ISSUE TITLE
Selenium 2.0 WebDriver

### ISSUE THREAD

**Issue by williamdewitt** [williamdewitt/gauge-csharp-selenium#6]
Please add a DriverFactory.cs file as per the gauge-example-csharp project

gauge-example-csharp/Implementation/DriverFactory.cs

**Comment by williamdewitt** [comment]
Soooo where is the file...

**Comment by ThebeRising** [comment]
I proposed the file. I assumed you'd double check it before you merged it.

**Comment by williamdewitt** [comment]
I don't see any proposals until you create the pull request...  Ill check it out now
